"""created reports

Revision ID: 25cdef2621bc
Revises: 81721858b0b7
Create Date: 2025-06-04 05:14:53.917192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '25cdef2621bc'
down_revision: Union[str, None] = '81721858b0b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_illegal_dump_reports_id', table_name='illegal_dump_reports')
    op.drop_table('illegal_dump_reports')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('illegal_dump_reports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('waste_type', postgresql.ENUM('PLASTIC', 'ELECTRONIC', 'ORGANIC', name='wastetypeenum'), autoincrement=False, nullable=False),
    sa.Column('severity', postgresql.ENUM('SMALL', 'MEDIUM', 'RISKING', 'DANGEROUS', name='severitylevelenum'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'ACCEPTED', 'REJECTED', name='reportstatusenum'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='illegal_dump_reports_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='illegal_dump_reports_pkey')
    )
    op.create_index('ix_illegal_dump_reports_id', 'illegal_dump_reports', ['id'], unique=False)
    # ### end Alembic commands ###
